/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessPendingRouteImport } from './routes/access-pending'
import { Route as AdminKppnRouteRouteImport } from './routes/admin-kppn/route'
import { Route as OperatorRouteRouteImport } from './routes/operator/route'
import { Route as SelectOrganizationRouteImport } from './routes/select-organization'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AdminKppnAccessRouteImport } from './routes/admin-kppn/access'
import { Route as AdminKppnAuditLogsRouteImport } from './routes/admin-kppn/audit-logs'
import { Route as AdminKppnDashboardRouteImport } from './routes/admin-kppn/dashboard'
import { Route as AdminKppnReportsRouteImport } from './routes/admin-kppn/reports'
import { Route as OperatorAnalysisRouteImport } from './routes/operator/analysis'
import { Route as OperatorDashboardRouteImport } from './routes/operator/dashboard'
import { Route as OperatorGuidesRouteImport } from './routes/operator/guides'
import { Route as OperatorHistoryRouteImport } from './routes/operator/history'
import { Route as OperatorImportRouteImport } from './routes/operator/import'
import { Route as OperatorRemindersRouteImport } from './routes/operator/reminders'
import { Route as OperatorReportsRouteImport } from './routes/operator/reports'
import { Route as OperatorSettingsRouteImport } from './routes/operator/settings'
import { Route as OperatorSimulationRouteImport } from './routes/operator/simulation'
import { Route as AdminKppnMonitoringRemindersRouteImport } from './routes/admin-kppn/monitoring/reminders'
import { Route as AdminKppnOrganizationsIndexRouteImport } from './routes/admin-kppn/organizations/index'
import { Route as AdminKppnOrganizationsOrgIdRouteImport } from './routes/admin-kppn/organizations/$orgId'
import { Route as AdminKppnPolicyHistoryRouteImport } from './routes/admin-kppn/policy/history'
import { Route as AdminKppnPolicyRemindersRouteImport } from './routes/admin-kppn/policy/reminders'
import { Route as AdminKppnPolicyWorkdaysRouteImport } from './routes/admin-kppn/policy/workdays'
import { Route as ApiQstashDailyRouteImport } from './routes/api/qstash/daily'
import { Route as ApiQstashSendRouteImport } from './routes/api/qstash/send'
import { Route as OperatorDataBudgetRevisionsRouteImport } from './routes/operator/data/budget-revisions'
import { Route as OperatorDataContractsInvoicesRouteImport } from './routes/operator/data/contracts-invoices'
import { Route as OperatorDataOutputAchievementRouteImport } from './routes/operator/data/output-achievement'
import { Route as OperatorDataRpdRealizationRouteImport } from './routes/operator/data/rpd-realization'
import { Route as OperatorDataSpmDispensationRouteImport } from './routes/operator/data/spm-dispensation'
import { Route as OperatorDataUpTupKkpRouteImport } from './routes/operator/data/up-tup-kkp'
import { Route as AdminKppnPolicyRuleSetsIndexRouteImport } from './routes/admin-kppn/policy/rule-sets/index'
import { Route as AdminKppnPolicyRuleSetsRuleSetIdRouteImport } from './routes/admin-kppn/policy/rule-sets/$ruleSetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessPendingRoute = AccessPendingRouteImport.update({
  id: '/access-pending',
  path: '/access-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKppnRouteRoute = AdminKppnRouteRouteImport.update({
  id: '/admin-kppn',
  path: '/admin-kppn',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRouteRoute = OperatorRouteRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectOrganizationRoute = SelectOrganizationRouteImport.update({
  id: '/select-organization',
  path: '/select-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKppnAccessRoute = AdminKppnAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AdminKppnRouteRoute,
} as any)
const AdminKppnAuditLogsRoute = AdminKppnAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminKppnRouteRoute,
} as any)
const AdminKppnDashboardRoute = AdminKppnDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminKppnRouteRoute,
} as any)
const AdminKppnReportsRoute = AdminKppnReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminKppnRouteRoute,
} as any)
const OperatorAnalysisRoute = OperatorAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => OperatorRouteRoute,
} as any)
const OperatorDashboardRoute = OperatorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OperatorRouteRoute,
} as any)
const OperatorGuidesRoute = OperatorGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => OperatorRouteRoute,
} as any)
const OperatorHistoryRoute = OperatorHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => OperatorRouteRoute,
} as any)
const OperatorImportRoute = OperatorImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => OperatorRouteRoute,
} as any)
const OperatorRemindersRoute = OperatorRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => OperatorRouteRoute,
} as any)
const OperatorReportsRoute = OperatorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OperatorRouteRoute,
} as any)
const OperatorSettingsRoute = OperatorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OperatorRouteRoute,
} as any)
const OperatorSimulationRoute = OperatorSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => OperatorRouteRoute,
} as any)
const AdminKppnMonitoringRemindersRoute =
  AdminKppnMonitoringRemindersRouteImport.update({
    id: '/monitoring/reminders',
    path: '/monitoring/reminders',
    getParentRoute: () => AdminKppnRouteRoute,
  } as any)
const AdminKppnOrganizationsIndexRoute =
  AdminKppnOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AdminKppnRouteRoute,
  } as any)
const AdminKppnOrganizationsOrgIdRoute =
  AdminKppnOrganizationsOrgIdRouteImport.update({
    id: '/organizations/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => AdminKppnRouteRoute,
  } as any)
const AdminKppnPolicyHistoryRoute = AdminKppnPolicyHistoryRouteImport.update({
  id: '/policy/history',
  path: '/policy/history',
  getParentRoute: () => AdminKppnRouteRoute,
} as any)
const AdminKppnPolicyRemindersRoute =
  AdminKppnPolicyRemindersRouteImport.update({
    id: '/policy/reminders',
    path: '/policy/reminders',
    getParentRoute: () => AdminKppnRouteRoute,
  } as any)
const AdminKppnPolicyWorkdaysRoute = AdminKppnPolicyWorkdaysRouteImport.update({
  id: '/policy/workdays',
  path: '/policy/workdays',
  getParentRoute: () => AdminKppnRouteRoute,
} as any)
const ApiQstashDailyRoute = ApiQstashDailyRouteImport.update({
  id: '/api/qstash/daily',
  path: '/api/qstash/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQstashSendRoute = ApiQstashSendRouteImport.update({
  id: '/api/qstash/send',
  path: '/api/qstash/send',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorDataBudgetRevisionsRoute =
  OperatorDataBudgetRevisionsRouteImport.update({
    id: '/data/budget-revisions',
    path: '/data/budget-revisions',
    getParentRoute: () => OperatorRouteRoute,
  } as any)
const OperatorDataContractsInvoicesRoute =
  OperatorDataContractsInvoicesRouteImport.update({
    id: '/data/contracts-invoices',
    path: '/data/contracts-invoices',
    getParentRoute: () => OperatorRouteRoute,
  } as any)
const OperatorDataOutputAchievementRoute =
  OperatorDataOutputAchievementRouteImport.update({
    id: '/data/output-achievement',
    path: '/data/output-achievement',
    getParentRoute: () => OperatorRouteRoute,
  } as any)
const OperatorDataRpdRealizationRoute =
  OperatorDataRpdRealizationRouteImport.update({
    id: '/data/rpd-realization',
    path: '/data/rpd-realization',
    getParentRoute: () => OperatorRouteRoute,
  } as any)
const OperatorDataSpmDispensationRoute =
  OperatorDataSpmDispensationRouteImport.update({
    id: '/data/spm-dispensation',
    path: '/data/spm-dispensation',
    getParentRoute: () => OperatorRouteRoute,
  } as any)
const OperatorDataUpTupKkpRoute = OperatorDataUpTupKkpRouteImport.update({
  id: '/data/up-tup-kkp',
  path: '/data/up-tup-kkp',
  getParentRoute: () => OperatorRouteRoute,
} as any)
const AdminKppnPolicyRuleSetsIndexRoute =
  AdminKppnPolicyRuleSetsIndexRouteImport.update({
    id: '/policy/rule-sets/',
    path: '/policy/rule-sets/',
    getParentRoute: () => AdminKppnRouteRoute,
  } as any)
const AdminKppnPolicyRuleSetsRuleSetIdRoute =
  AdminKppnPolicyRuleSetsRuleSetIdRouteImport.update({
    id: '/policy/rule-sets/$ruleSetId',
    path: '/policy/rule-sets/$ruleSetId',
    getParentRoute: () => AdminKppnRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-kppn': typeof AdminKppnRouteRouteWithChildren
  '/operator': typeof OperatorRouteRouteWithChildren
  '/access-pending': typeof AccessPendingRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/sign-in': typeof SignInRoute
  '/admin-kppn/access': typeof AdminKppnAccessRoute
  '/admin-kppn/audit-logs': typeof AdminKppnAuditLogsRoute
  '/admin-kppn/dashboard': typeof AdminKppnDashboardRoute
  '/admin-kppn/reports': typeof AdminKppnReportsRoute
  '/operator/analysis': typeof OperatorAnalysisRoute
  '/operator/dashboard': typeof OperatorDashboardRoute
  '/operator/guides': typeof OperatorGuidesRoute
  '/operator/history': typeof OperatorHistoryRoute
  '/operator/import': typeof OperatorImportRoute
  '/operator/reminders': typeof OperatorRemindersRoute
  '/operator/reports': typeof OperatorReportsRoute
  '/operator/settings': typeof OperatorSettingsRoute
  '/operator/simulation': typeof OperatorSimulationRoute
  '/admin-kppn/monitoring/reminders': typeof AdminKppnMonitoringRemindersRoute
  '/admin-kppn/organizations/$orgId': typeof AdminKppnOrganizationsOrgIdRoute
  '/admin-kppn/policy/history': typeof AdminKppnPolicyHistoryRoute
  '/admin-kppn/policy/reminders': typeof AdminKppnPolicyRemindersRoute
  '/admin-kppn/policy/workdays': typeof AdminKppnPolicyWorkdaysRoute
  '/api/qstash/daily': typeof ApiQstashDailyRoute
  '/api/qstash/send': typeof ApiQstashSendRoute
  '/operator/data/budget-revisions': typeof OperatorDataBudgetRevisionsRoute
  '/operator/data/contracts-invoices': typeof OperatorDataContractsInvoicesRoute
  '/operator/data/output-achievement': typeof OperatorDataOutputAchievementRoute
  '/operator/data/rpd-realization': typeof OperatorDataRpdRealizationRoute
  '/operator/data/spm-dispensation': typeof OperatorDataSpmDispensationRoute
  '/operator/data/up-tup-kkp': typeof OperatorDataUpTupKkpRoute
  '/admin-kppn/organizations/': typeof AdminKppnOrganizationsIndexRoute
  '/admin-kppn/policy/rule-sets/$ruleSetId': typeof AdminKppnPolicyRuleSetsRuleSetIdRoute
  '/admin-kppn/policy/rule-sets/': typeof AdminKppnPolicyRuleSetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-kppn': typeof AdminKppnRouteRouteWithChildren
  '/operator': typeof OperatorRouteRouteWithChildren
  '/access-pending': typeof AccessPendingRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/sign-in': typeof SignInRoute
  '/admin-kppn/access': typeof AdminKppnAccessRoute
  '/admin-kppn/audit-logs': typeof AdminKppnAuditLogsRoute
  '/admin-kppn/dashboard': typeof AdminKppnDashboardRoute
  '/admin-kppn/reports': typeof AdminKppnReportsRoute
  '/operator/analysis': typeof OperatorAnalysisRoute
  '/operator/dashboard': typeof OperatorDashboardRoute
  '/operator/guides': typeof OperatorGuidesRoute
  '/operator/history': typeof OperatorHistoryRoute
  '/operator/import': typeof OperatorImportRoute
  '/operator/reminders': typeof OperatorRemindersRoute
  '/operator/reports': typeof OperatorReportsRoute
  '/operator/settings': typeof OperatorSettingsRoute
  '/operator/simulation': typeof OperatorSimulationRoute
  '/admin-kppn/monitoring/reminders': typeof AdminKppnMonitoringRemindersRoute
  '/admin-kppn/organizations/$orgId': typeof AdminKppnOrganizationsOrgIdRoute
  '/admin-kppn/policy/history': typeof AdminKppnPolicyHistoryRoute
  '/admin-kppn/policy/reminders': typeof AdminKppnPolicyRemindersRoute
  '/admin-kppn/policy/workdays': typeof AdminKppnPolicyWorkdaysRoute
  '/api/qstash/daily': typeof ApiQstashDailyRoute
  '/api/qstash/send': typeof ApiQstashSendRoute
  '/operator/data/budget-revisions': typeof OperatorDataBudgetRevisionsRoute
  '/operator/data/contracts-invoices': typeof OperatorDataContractsInvoicesRoute
  '/operator/data/output-achievement': typeof OperatorDataOutputAchievementRoute
  '/operator/data/rpd-realization': typeof OperatorDataRpdRealizationRoute
  '/operator/data/spm-dispensation': typeof OperatorDataSpmDispensationRoute
  '/operator/data/up-tup-kkp': typeof OperatorDataUpTupKkpRoute
  '/admin-kppn/organizations': typeof AdminKppnOrganizationsIndexRoute
  '/admin-kppn/policy/rule-sets/$ruleSetId': typeof AdminKppnPolicyRuleSetsRuleSetIdRoute
  '/admin-kppn/policy/rule-sets': typeof AdminKppnPolicyRuleSetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-kppn': typeof AdminKppnRouteRouteWithChildren
  '/operator': typeof OperatorRouteRouteWithChildren
  '/access-pending': typeof AccessPendingRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/sign-in': typeof SignInRoute
  '/admin-kppn/access': typeof AdminKppnAccessRoute
  '/admin-kppn/audit-logs': typeof AdminKppnAuditLogsRoute
  '/admin-kppn/dashboard': typeof AdminKppnDashboardRoute
  '/admin-kppn/reports': typeof AdminKppnReportsRoute
  '/operator/analysis': typeof OperatorAnalysisRoute
  '/operator/dashboard': typeof OperatorDashboardRoute
  '/operator/guides': typeof OperatorGuidesRoute
  '/operator/history': typeof OperatorHistoryRoute
  '/operator/import': typeof OperatorImportRoute
  '/operator/reminders': typeof OperatorRemindersRoute
  '/operator/reports': typeof OperatorReportsRoute
  '/operator/settings': typeof OperatorSettingsRoute
  '/operator/simulation': typeof OperatorSimulationRoute
  '/admin-kppn/monitoring/reminders': typeof AdminKppnMonitoringRemindersRoute
  '/admin-kppn/organizations/$orgId': typeof AdminKppnOrganizationsOrgIdRoute
  '/admin-kppn/policy/history': typeof AdminKppnPolicyHistoryRoute
  '/admin-kppn/policy/reminders': typeof AdminKppnPolicyRemindersRoute
  '/admin-kppn/policy/workdays': typeof AdminKppnPolicyWorkdaysRoute
  '/api/qstash/daily': typeof ApiQstashDailyRoute
  '/api/qstash/send': typeof ApiQstashSendRoute
  '/operator/data/budget-revisions': typeof OperatorDataBudgetRevisionsRoute
  '/operator/data/contracts-invoices': typeof OperatorDataContractsInvoicesRoute
  '/operator/data/output-achievement': typeof OperatorDataOutputAchievementRoute
  '/operator/data/rpd-realization': typeof OperatorDataRpdRealizationRoute
  '/operator/data/spm-dispensation': typeof OperatorDataSpmDispensationRoute
  '/operator/data/up-tup-kkp': typeof OperatorDataUpTupKkpRoute
  '/admin-kppn/organizations/': typeof AdminKppnOrganizationsIndexRoute
  '/admin-kppn/policy/rule-sets/$ruleSetId': typeof AdminKppnPolicyRuleSetsRuleSetIdRoute
  '/admin-kppn/policy/rule-sets/': typeof AdminKppnPolicyRuleSetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-kppn'
    | '/operator'
    | '/access-pending'
    | '/select-organization'
    | '/sign-in'
    | '/admin-kppn/access'
    | '/admin-kppn/audit-logs'
    | '/admin-kppn/dashboard'
    | '/admin-kppn/reports'
    | '/operator/analysis'
    | '/operator/dashboard'
    | '/operator/guides'
    | '/operator/history'
    | '/operator/import'
    | '/operator/reminders'
    | '/operator/reports'
    | '/operator/settings'
    | '/operator/simulation'
    | '/admin-kppn/monitoring/reminders'
    | '/admin-kppn/organizations/$orgId'
    | '/admin-kppn/policy/history'
    | '/admin-kppn/policy/reminders'
    | '/admin-kppn/policy/workdays'
    | '/api/qstash/daily'
    | '/api/qstash/send'
    | '/operator/data/budget-revisions'
    | '/operator/data/contracts-invoices'
    | '/operator/data/output-achievement'
    | '/operator/data/rpd-realization'
    | '/operator/data/spm-dispensation'
    | '/operator/data/up-tup-kkp'
    | '/admin-kppn/organizations/'
    | '/admin-kppn/policy/rule-sets/$ruleSetId'
    | '/admin-kppn/policy/rule-sets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-kppn'
    | '/operator'
    | '/access-pending'
    | '/select-organization'
    | '/sign-in'
    | '/admin-kppn/access'
    | '/admin-kppn/audit-logs'
    | '/admin-kppn/dashboard'
    | '/admin-kppn/reports'
    | '/operator/analysis'
    | '/operator/dashboard'
    | '/operator/guides'
    | '/operator/history'
    | '/operator/import'
    | '/operator/reminders'
    | '/operator/reports'
    | '/operator/settings'
    | '/operator/simulation'
    | '/admin-kppn/monitoring/reminders'
    | '/admin-kppn/organizations/$orgId'
    | '/admin-kppn/policy/history'
    | '/admin-kppn/policy/reminders'
    | '/admin-kppn/policy/workdays'
    | '/api/qstash/daily'
    | '/api/qstash/send'
    | '/operator/data/budget-revisions'
    | '/operator/data/contracts-invoices'
    | '/operator/data/output-achievement'
    | '/operator/data/rpd-realization'
    | '/operator/data/spm-dispensation'
    | '/operator/data/up-tup-kkp'
    | '/admin-kppn/organizations'
    | '/admin-kppn/policy/rule-sets/$ruleSetId'
    | '/admin-kppn/policy/rule-sets'
  id:
    | '__root__'
    | '/'
    | '/admin-kppn'
    | '/operator'
    | '/access-pending'
    | '/select-organization'
    | '/sign-in'
    | '/admin-kppn/access'
    | '/admin-kppn/audit-logs'
    | '/admin-kppn/dashboard'
    | '/admin-kppn/reports'
    | '/operator/analysis'
    | '/operator/dashboard'
    | '/operator/guides'
    | '/operator/history'
    | '/operator/import'
    | '/operator/reminders'
    | '/operator/reports'
    | '/operator/settings'
    | '/operator/simulation'
    | '/admin-kppn/monitoring/reminders'
    | '/admin-kppn/organizations/$orgId'
    | '/admin-kppn/policy/history'
    | '/admin-kppn/policy/reminders'
    | '/admin-kppn/policy/workdays'
    | '/api/qstash/daily'
    | '/api/qstash/send'
    | '/operator/data/budget-revisions'
    | '/operator/data/contracts-invoices'
    | '/operator/data/output-achievement'
    | '/operator/data/rpd-realization'
    | '/operator/data/spm-dispensation'
    | '/operator/data/up-tup-kkp'
    | '/admin-kppn/organizations/'
    | '/admin-kppn/policy/rule-sets/$ruleSetId'
    | '/admin-kppn/policy/rule-sets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminKppnRouteRoute: typeof AdminKppnRouteRouteWithChildren
  OperatorRouteRoute: typeof OperatorRouteRouteWithChildren
  AccessPendingRoute: typeof AccessPendingRoute
  SelectOrganizationRoute: typeof SelectOrganizationRoute
  SignInRoute: typeof SignInRoute
  ApiQstashDailyRoute: typeof ApiQstashDailyRoute
  ApiQstashSendRoute: typeof ApiQstashSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-pending': {
      id: '/access-pending'
      path: '/access-pending'
      fullPath: '/access-pending'
      preLoaderRoute: typeof AccessPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-kppn': {
      id: '/admin-kppn'
      path: '/admin-kppn'
      fullPath: '/admin-kppn'
      preLoaderRoute: typeof AdminKppnRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-organization': {
      id: '/select-organization'
      path: '/select-organization'
      fullPath: '/select-organization'
      preLoaderRoute: typeof SelectOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-kppn/access': {
      id: '/admin-kppn/access'
      path: '/access'
      fullPath: '/admin-kppn/access'
      preLoaderRoute: typeof AdminKppnAccessRouteImport
      parentRoute: typeof AdminKppnRouteRoute
    }
    '/admin-kppn/audit-logs': {
      id: '/admin-kppn/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin-kppn/audit-logs'
      preLoaderRoute: typeof AdminKppnAuditLogsRouteImport
      parentRoute: typeof AdminKppnRouteRoute
    }
    '/admin-kppn/dashboard': {
      id: '/admin-kppn/dashboard'
      path: '/dashboard'
      fullPath: '/admin-kppn/dashboard'
      preLoaderRoute: typeof AdminKppnDashboardRouteImport
      parentRoute: typeof AdminKppnRouteRoute
    }
    '/admin-kppn/reports': {
      id: '/admin-kppn/reports'
      path: '/reports'
      fullPath: '/admin-kppn/reports'
      preLoaderRoute: typeof AdminKppnReportsRouteImport
      parentRoute: typeof AdminKppnRouteRoute
    }
    '/operator/analysis': {
      id: '/operator/analysis'
      path: '/analysis'
      fullPath: '/operator/analysis'
      preLoaderRoute: typeof OperatorAnalysisRouteImport
      parentRoute: typeof OperatorRouteRoute
    }
    '/operator/dashboard': {
      id: '/operator/dashboard'
      path: '/dashboard'
      fullPath: '/operator/dashboard'
      preLoaderRoute: typeof OperatorDashboardRouteImport
      parentRoute: typeof OperatorRouteRoute
    }
    '/operator/guides': {
      id: '/operator/guides'
      path: '/guides'
      fullPath: '/operator/guides'
      preLoaderRoute: typeof OperatorGuidesRouteImport
      parentRoute: typeof OperatorRouteRoute
    }
    '/operator/history': {
      id: '/operator/history'
      path: '/history'
      fullPath: '/operator/history'
      preLoaderRoute: typeof OperatorHistoryRouteImport
      parentRoute: typeof OperatorRouteRoute
    }
    '/operator/import': {
      id: '/operator/import'
      path: '/import'
      fullPath: '/operator/import'
      preLoaderRoute: typeof OperatorImportRouteImport
      parentRoute: typeof OperatorRouteRoute
    }
    '/operator/reminders': {
      id: '/operator/reminders'
      path: '/reminders'
      fullPath: '/operator/reminders'
      preLoaderRoute: typeof OperatorRemindersRouteImport
      parentRoute: typeof OperatorRouteRoute
    }
    '/operator/reports': {
      id: '/operator/reports'
      path: '/reports'
      fullPath: '/operator/reports'
      preLoaderRoute: typeof OperatorReportsRouteImport
      parentRoute: typeof OperatorRouteRoute
    }
    '/operator/settings': {
      id: '/operator/settings'
      path: '/settings'
      fullPath: '/operator/settings'
      preLoaderRoute: typeof OperatorSettingsRouteImport
      parentRoute: typeof OperatorRouteRoute
    }
    '/operator/simulation': {
      id: '/operator/simulation'
      path: '/simulation'
      fullPath: '/operator/simulation'
      preLoaderRoute: typeof OperatorSimulationRouteImport
      parentRoute: typeof OperatorRouteRoute
    }
    '/admin-kppn/monitoring/reminders': {
      id: '/admin-kppn/monitoring/reminders'
      path: '/monitoring/reminders'
      fullPath: '/admin-kppn/monitoring/reminders'
      preLoaderRoute: typeof AdminKppnMonitoringRemindersRouteImport
      parentRoute: typeof AdminKppnRouteRoute
    }
    '/admin-kppn/organizations/': {
      id: '/admin-kppn/organizations/'
      path: '/organizations'
      fullPath: '/admin-kppn/organizations/'
      preLoaderRoute: typeof AdminKppnOrganizationsIndexRouteImport
      parentRoute: typeof AdminKppnRouteRoute
    }
    '/admin-kppn/organizations/$orgId': {
      id: '/admin-kppn/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/admin-kppn/organizations/$orgId'
      preLoaderRoute: typeof AdminKppnOrganizationsOrgIdRouteImport
      parentRoute: typeof AdminKppnRouteRoute
    }
    '/admin-kppn/policy/history': {
      id: '/admin-kppn/policy/history'
      path: '/policy/history'
      fullPath: '/admin-kppn/policy/history'
      preLoaderRoute: typeof AdminKppnPolicyHistoryRouteImport
      parentRoute: typeof AdminKppnRouteRoute
    }
    '/admin-kppn/policy/reminders': {
      id: '/admin-kppn/policy/reminders'
      path: '/policy/reminders'
      fullPath: '/admin-kppn/policy/reminders'
      preLoaderRoute: typeof AdminKppnPolicyRemindersRouteImport
      parentRoute: typeof AdminKppnRouteRoute
    }
    '/admin-kppn/policy/workdays': {
      id: '/admin-kppn/policy/workdays'
      path: '/policy/workdays'
      fullPath: '/admin-kppn/policy/workdays'
      preLoaderRoute: typeof AdminKppnPolicyWorkdaysRouteImport
      parentRoute: typeof AdminKppnRouteRoute
    }
    '/api/qstash/daily': {
      id: '/api/qstash/daily'
      path: '/api/qstash/daily'
      fullPath: '/api/qstash/daily'
      preLoaderRoute: typeof ApiQstashDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qstash/send': {
      id: '/api/qstash/send'
      path: '/api/qstash/send'
      fullPath: '/api/qstash/send'
      preLoaderRoute: typeof ApiQstashSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/data/budget-revisions': {
      id: '/operator/data/budget-revisions'
      path: '/data/budget-revisions'
      fullPath: '/operator/data/budget-revisions'
      preLoaderRoute: typeof OperatorDataBudgetRevisionsRouteImport
      parentRoute: typeof OperatorRouteRoute
    }
    '/operator/data/contracts-invoices': {
      id: '/operator/data/contracts-invoices'
      path: '/data/contracts-invoices'
      fullPath: '/operator/data/contracts-invoices'
      preLoaderRoute: typeof OperatorDataContractsInvoicesRouteImport
      parentRoute: typeof OperatorRouteRoute
    }
    '/operator/data/output-achievement': {
      id: '/operator/data/output-achievement'
      path: '/data/output-achievement'
      fullPath: '/operator/data/output-achievement'
      preLoaderRoute: typeof OperatorDataOutputAchievementRouteImport
      parentRoute: typeof OperatorRouteRoute
    }
    '/operator/data/rpd-realization': {
      id: '/operator/data/rpd-realization'
      path: '/data/rpd-realization'
      fullPath: '/operator/data/rpd-realization'
      preLoaderRoute: typeof OperatorDataRpdRealizationRouteImport
      parentRoute: typeof OperatorRouteRoute
    }
    '/operator/data/spm-dispensation': {
      id: '/operator/data/spm-dispensation'
      path: '/data/spm-dispensation'
      fullPath: '/operator/data/spm-dispensation'
      preLoaderRoute: typeof OperatorDataSpmDispensationRouteImport
      parentRoute: typeof OperatorRouteRoute
    }
    '/operator/data/up-tup-kkp': {
      id: '/operator/data/up-tup-kkp'
      path: '/data/up-tup-kkp'
      fullPath: '/operator/data/up-tup-kkp'
      preLoaderRoute: typeof OperatorDataUpTupKkpRouteImport
      parentRoute: typeof OperatorRouteRoute
    }
    '/admin-kppn/policy/rule-sets/': {
      id: '/admin-kppn/policy/rule-sets/'
      path: '/policy/rule-sets'
      fullPath: '/admin-kppn/policy/rule-sets/'
      preLoaderRoute: typeof AdminKppnPolicyRuleSetsIndexRouteImport
      parentRoute: typeof AdminKppnRouteRoute
    }
    '/admin-kppn/policy/rule-sets/$ruleSetId': {
      id: '/admin-kppn/policy/rule-sets/$ruleSetId'
      path: '/policy/rule-sets/$ruleSetId'
      fullPath: '/admin-kppn/policy/rule-sets/$ruleSetId'
      preLoaderRoute: typeof AdminKppnPolicyRuleSetsRuleSetIdRouteImport
      parentRoute: typeof AdminKppnRouteRoute
    }
  }
}

interface AdminKppnRouteRouteChildren {
  AdminKppnAccessRoute: typeof AdminKppnAccessRoute
  AdminKppnAuditLogsRoute: typeof AdminKppnAuditLogsRoute
  AdminKppnDashboardRoute: typeof AdminKppnDashboardRoute
  AdminKppnReportsRoute: typeof AdminKppnReportsRoute
  AdminKppnMonitoringRemindersRoute: typeof AdminKppnMonitoringRemindersRoute
  AdminKppnOrganizationsOrgIdRoute: typeof AdminKppnOrganizationsOrgIdRoute
  AdminKppnPolicyHistoryRoute: typeof AdminKppnPolicyHistoryRoute
  AdminKppnPolicyRemindersRoute: typeof AdminKppnPolicyRemindersRoute
  AdminKppnPolicyWorkdaysRoute: typeof AdminKppnPolicyWorkdaysRoute
  AdminKppnOrganizationsIndexRoute: typeof AdminKppnOrganizationsIndexRoute
  AdminKppnPolicyRuleSetsRuleSetIdRoute: typeof AdminKppnPolicyRuleSetsRuleSetIdRoute
  AdminKppnPolicyRuleSetsIndexRoute: typeof AdminKppnPolicyRuleSetsIndexRoute
}

const AdminKppnRouteRouteChildren: AdminKppnRouteRouteChildren = {
  AdminKppnAccessRoute: AdminKppnAccessRoute,
  AdminKppnAuditLogsRoute: AdminKppnAuditLogsRoute,
  AdminKppnDashboardRoute: AdminKppnDashboardRoute,
  AdminKppnReportsRoute: AdminKppnReportsRoute,
  AdminKppnMonitoringRemindersRoute: AdminKppnMonitoringRemindersRoute,
  AdminKppnOrganizationsOrgIdRoute: AdminKppnOrganizationsOrgIdRoute,
  AdminKppnPolicyHistoryRoute: AdminKppnPolicyHistoryRoute,
  AdminKppnPolicyRemindersRoute: AdminKppnPolicyRemindersRoute,
  AdminKppnPolicyWorkdaysRoute: AdminKppnPolicyWorkdaysRoute,
  AdminKppnOrganizationsIndexRoute: AdminKppnOrganizationsIndexRoute,
  AdminKppnPolicyRuleSetsRuleSetIdRoute: AdminKppnPolicyRuleSetsRuleSetIdRoute,
  AdminKppnPolicyRuleSetsIndexRoute: AdminKppnPolicyRuleSetsIndexRoute,
}

const AdminKppnRouteRouteWithChildren = AdminKppnRouteRoute._addFileChildren(
  AdminKppnRouteRouteChildren,
)

interface OperatorRouteRouteChildren {
  OperatorAnalysisRoute: typeof OperatorAnalysisRoute
  OperatorDashboardRoute: typeof OperatorDashboardRoute
  OperatorGuidesRoute: typeof OperatorGuidesRoute
  OperatorHistoryRoute: typeof OperatorHistoryRoute
  OperatorImportRoute: typeof OperatorImportRoute
  OperatorRemindersRoute: typeof OperatorRemindersRoute
  OperatorReportsRoute: typeof OperatorReportsRoute
  OperatorSettingsRoute: typeof OperatorSettingsRoute
  OperatorSimulationRoute: typeof OperatorSimulationRoute
  OperatorDataBudgetRevisionsRoute: typeof OperatorDataBudgetRevisionsRoute
  OperatorDataContractsInvoicesRoute: typeof OperatorDataContractsInvoicesRoute
  OperatorDataOutputAchievementRoute: typeof OperatorDataOutputAchievementRoute
  OperatorDataRpdRealizationRoute: typeof OperatorDataRpdRealizationRoute
  OperatorDataSpmDispensationRoute: typeof OperatorDataSpmDispensationRoute
  OperatorDataUpTupKkpRoute: typeof OperatorDataUpTupKkpRoute
}

const OperatorRouteRouteChildren: OperatorRouteRouteChildren = {
  OperatorAnalysisRoute: OperatorAnalysisRoute,
  OperatorDashboardRoute: OperatorDashboardRoute,
  OperatorGuidesRoute: OperatorGuidesRoute,
  OperatorHistoryRoute: OperatorHistoryRoute,
  OperatorImportRoute: OperatorImportRoute,
  OperatorRemindersRoute: OperatorRemindersRoute,
  OperatorReportsRoute: OperatorReportsRoute,
  OperatorSettingsRoute: OperatorSettingsRoute,
  OperatorSimulationRoute: OperatorSimulationRoute,
  OperatorDataBudgetRevisionsRoute: OperatorDataBudgetRevisionsRoute,
  OperatorDataContractsInvoicesRoute: OperatorDataContractsInvoicesRoute,
  OperatorDataOutputAchievementRoute: OperatorDataOutputAchievementRoute,
  OperatorDataRpdRealizationRoute: OperatorDataRpdRealizationRoute,
  OperatorDataSpmDispensationRoute: OperatorDataSpmDispensationRoute,
  OperatorDataUpTupKkpRoute: OperatorDataUpTupKkpRoute,
}

const OperatorRouteRouteWithChildren = OperatorRouteRoute._addFileChildren(
  OperatorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminKppnRouteRoute: AdminKppnRouteRouteWithChildren,
  OperatorRouteRoute: OperatorRouteRouteWithChildren,
  AccessPendingRoute: AccessPendingRoute,
  SelectOrganizationRoute: SelectOrganizationRoute,
  SignInRoute: SignInRoute,
  ApiQstashDailyRoute: ApiQstashDailyRoute,
  ApiQstashSendRoute: ApiQstashSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
